### ISSUE TITLE
Game crash suddenly

### ISSUE THREAD

**Issue by IsaDucko** [sleepingdragoninn/antique-atlas#141]
I do have a lot of mods, but the suspected mods says antique atlas + survey stones, (also fabric lifestyle cycles which has to do with having the wrong version of a mod apparently?)

Found out it happens when I get close to villages

https://pastebin.com/UUhku8fW

**Comment by sleepingdragoninn** [comment]
Looks like you have a mod that's registering a structure with a null type - we'll patch this so it logs a warning instead of crashing the whole game.

**Comment by IsaDucko** [comment]
tyty, also how do i add custom structure icons? I think i read it somewhere but i cant find it anymore

**Comment by watermelon0guy** [comment]
@sisby-folk I think it's the same problem. It looks like it's caused by [ChoiceTheorem's Overhauled Village](https://modrinth.com/mod/ct-overhaul-village)
Video with bug:
https://youtu.be/IogoEjFC6M8
Crash report:
[crash-2024-06-24_04.04.46-server.txt](https://github.com/user-attachments/files/15958074/crash-2024-06-24_04.04.46-server.txt)

**Comment by sleepingdragoninn** [comment]
@Duckkoi https://github.com/sisby-folk/antique-atlas/wiki
