### ISSUE TITLE
Map not opening?

### ISSUE THREAD

**Issue by SireAwfulThe1st** [sleepingdragoninn/antique-atlas#21]
Suddenly the atlas isn't opening at all, not sure what happened, tried lookin' at the configs and nothing has a keybind conflict with the original keybind of AA (M) either, if it helps, I'm using AA 1.1.4+1.20 which are like the most recent version.

**Comment by sleepingdragoninn** [comment]
if you're on forge, you're likely just missing that 1.x doesn't require cloth or architectury, but instead requires connector and forgified fabric api

unfortunately, there's no way (yet) for us to flag this to forge's modloader itself or on modrinth.

otherwise, feel free to upload your `logs/latest.log` to https://mclo.gs/ and post them here

**Comment by SireAwfulThe1st** [comment]
Didn't know that it's now a fabric mod that requires sintyra connector, kinda sad that it was a sudden change but oh well. Gotta rely on memory for remembering places again hahaha. At least I appreciate the info.

**Comment by sleepingdragoninn** [comment]
To clarify in detail, this project is an in-progress partial rewrite of the mod, and its easier to work on a rewrite on a single platform instead of multiple / using arch api.

When it's done, we'll be looking at native ports (not arch api based - native branches)  - we marked 1.1.4+1.20 as forge compatible because we found it worked perfectly on connector and has small fixes and internal improvements over 0.x as part of the rewrite - just use 0.x if you prefer to use an arch mod instead of a connector one.

**Comment by IdrisQe** [comment]
I wouldn't reccommend tagging it as Forge then. Sinytra Connector runs Fabric mods on Forge, so it's still entirely a Fabric Mod. If anything you could add a line to the description mentioning that it has been tested and works correctly with Sinytra Connector if you want to use it on Forge.
