### ISSUE TITLE
Feature request: (Re-)Add Antique Atlas book

### ISSUE THREAD

**Issue by DariCari** [sleepingdragoninn/antique-atlas#92]
I would find it cool if the user can decide in the config to switch to the og book instead of having a hotkey. That is what the mod was all about: Having an atlas with you **instead** of a minimap that you can open at any time.

Thank you :)

**Comment by sleepingdragoninn** [comment]
covered by #86! A literal item is impossible for a client-side mod, but the classic "holding up a map in your hands" mode sounds fun to implement.

**Comment by TheOverpassArsonist** [comment]
For what it's worth I think there's merit in having this be optionally server side for a real item as well.

Subjectively, depending on the modpack it may make more sense. Personally one of the main things I used antique atlas for before was specifically that it wasn't a standard minimap and still required more consideration.

There are quite a few objective downsides too with strictly adhering to client-side only. Notably, if you use a mod that changes how items are held (such as a first-person view mod) then you need to add a specific exception to **_all_** books for the held-functionality to even work at all. Additionally you can't (for example) right click while holding the 'antique atlas' book to open the menu, it has an icon that's just a normal book, it won't be correctly seen as a unique item by other mods, (I can't think of a specific case where this would be a problem, but I just know that's one of those areas that would cause some very annoying issues. Like if you have a mod that adds servant golems or something and you say 'get me a book' and they bring your 'antique atlas' because it is, technically, a book.) etc.

While I do understand the rationality behind wanting it to work entirely clientside, I think quite a lot is lost by having that be a _strict_ requirement. There are usecases where having an actual item makes more sense and, while I can see why you wouldn't want to make it a _**requirement**_ for it to be installed server-side, I definitely think it should at least be considered as an option so that users, packdesigners, etc. can pick what behaviours they want.

An example would be having it so that, _if_ the mod is installed server-side, it adds an item and then you could add additional configuration options like 'require item to use map' or 'save map contents per-item or per-player' or so on. Strictly avoiding adding things that wouldn't be entirely-clientside seems like it's missing a lot of opportunity.
